### ISSUE TITLE
PTrack and Pozyx tracking integration and calibration

### ISSUE THREAD

**Issue by benloh** [theRAPTLab/gsgo#114]
In GitLab by @jdanish on Apr 29, 2021, 06:11

# Design Issues

Now:

* [x] Mapping to blueprints -- How do you select which blueprint / agent you control?
* [x] Setting Transforms
* [x] Don't send entity update messages if TrackerSetup is not active -- see api-inputs.StartTrackerVisuals
* [x] Add "acceleromoter" data to mqtt stream
* [ ] Handle tag sleeping
  * [x] Tags emitting bad data during sleep
  * [ ] Tags wake up awkwardly

After Locale Storage
* [ ] Set Pozyx server IP
* [ ] Saving Transforms and IP (e.g. transforms for specific locations ala PLAE)

Future
* [ ] Customizable jitter handling?
* [ ] Handling Aging / Disconnects
* [ ] Debugging Data Object display
* [ ] Refactor?  Remove TrackerSetup dependency on Main?  -- Not easy to do because rendering is based on a project being loaded.

Future?:

* [ ] Cursor control -- Handle inputs as cursors, not direct agent controllers?

# Mapping

Methods:
1. Auto-assign to specific blueprint upon appearance
2. Popup menu selects blueprint for new entities appearing
3. Pozyx id defines specific blueprint
4. Walk through a rectangle to select a blueprint
5. Hit Pozyx button to cycle through available blueprints
6. Script/Project setting determines auto-assignment -- e.g. Fish can be any input, but Pozyx always maps to algae?
7. Cursor: Walk through agent to pick it up.

# Wearable Tags

#### Sleeping

By default, tags go to sleep after 25 blinks.  The blink rate is defined by the Aloha TODA rate (max of 24 Hz).
When they're asleep, they will periodically still emit a location every 50 blinks.  But these locations often have bad position data (e.g. well out of bounds).

What should we do?
* Can we detect a sleeping message? -- Not directly, but we can use accelerometer values of < 250 mg
* Can we ignore out of bounds updates? -- Values are not always out of bounds.  
* Should we not allow the tags to sleep for a long time? -- This would use up batteries.

Solution
This seems to work: Ignore updates > 0.25 (normalized units) while accelerometer < 250mg.
