### ISSUE TITLE
STUDENTS_MAY_CHANGE

### ISSUE THREAD

**Issue by benloh** [theRAPTLab/gsgo#287]
A review of variables that students may change.

# TO DO 

#### aquatic

* [x] `addProp` -- workaround is to add a second `prop xxx setTo nnn` line.
* [x] `featCall Movement setMovementType 'wander' 0.2` -- workaround is to use featProp to set the distance, e.g.
```
featProp Movement movementType setTo 'wander'
featProp Movement distance setTo 0.2
```

#### decomp

* [X] `featCall AgentWidgets bindMeterTo nutrients` -- use `featProp Agentwidgets meterProp setTo nutrients`.  Students will still have to type in the variable name.
* [x] `featCall Population countAgentProp 'Plant' 'energyLevel'` -- change this into a featProp.  See #287.
* [x] `prop Plant.matter sub 10` -- Need GVarElement support for objrefs.  See #292.
* [x] `prop x addRnd -20 20` -- Need GVarElement support for other methods.  See #293.

#### moths-one

* [X] TreeTrunk color: `featCall Costume setColorizeHSV 0 0 0.66` -- @coreybrady the fix here is to set each HSV parameters separately, e.g. 
```
  featProp Costume colorHue setTo 0
  featProp Costume colorSaturation setTo 0
  featProp Costume colorValue setTo 0.66
```

* [X] Number of Moths -- @coreybrady depending on what you're looking for, the solution is probably to start with one moth, set a target population size, and use Population `populateBySpawning during the round intro to set the number of moths.  Please create a new issue if you want to discuss this.

* [X] Number or Color Scale steps -- @coreybrady if this is important we can probably turn the number of steps into a featProp.  Currently the steps are created via a featCall parameter and we do not currently  have support for changing featCall parameters.  Please create a new issue if you want a featProp workaround.  Steps can now be defined via !143.

#### moths-two

* [X] Mutation: `prop colorIndx addRnd -1 1 true` -- !142 adds a new `addRndInt` that is script UI editable.

#### moths-three
