### ISSUE TITLE
CODE STANDARDS CHECKLIST (WIP)

### ISSUE THREAD

**Issue by benloh** [theRAPTLab/gsgo#399]
Sri is codifying the past 7 years of our programming code style in one place so they can assign fancy numbers to them or something. Plus they keep seeing these issues pop up over and over, so this indicates that maybe they are not clearly stated.

GENERAL CONVERSIONS

* [ ] convert `export function FName` to `export { FName }` at the end of the module, so it's easier to see everything at the end
* [ ] for exports, ensure there is a short description and that they are exported in functional groups when it make sense. `transpiler-v2` is an example of this
* [ ] Convert any relative references in `import` statements to the path alias style. The available path aliases (like 'modules' and 'script') are defined `gem-srv.tsconfig.json`
* [ ] use jsdoc `/** API: description`  for any code that is an API method that's being exported. Everything else should use `m_FunctionName` syntax, and also be noted as `/** support: desc`
* [ ] Ensure that the left paragraph of a jsdoc comment aligns by using a TAB on the lines after the initial `/**` opener.
* [ ] Check that you have removed extraneous console.log output by setting the module's `DBG` flag or commenting them out.

BONUS: GENERAL CONVENTIONS

* [ ] module imports now use the `import * as MODNAME from ...`, not `import { MethodA } from ...`
* [ ] module exports should be in groups of related items with comments (see transpiler for example)
* [ ] module-scoped support functions are of the form `function m_SupportMethodName ()`
* [ ] module-scoped dictionaries and constants are of the form `SOMETHING_DICT`
* [ ] module-scoped variables are of the form `m_variable_name`
* [ ] function parameters are of the form `function (aVar, bSomeOtherVar)`
* [ ] function-scoped variables are of the form `snake_case_var`
* [ ] functions defined functions use form `f_function_name` or `u_function_name` (u stands for utility)

BONUS: STYLE CONVENTIONS LOOSELY KEPT

* [ ] functions that return a parameterized result are named `GetTypeOfResult(param)`
* [ ] functions that for return a singleton or unique system entity do not use `Get` as a prefix
* [ ] functions that perform an imperative action are named `VerbTheThing()`
* [ ] functions that returns a promise are named `PromiseTypeOfResult`
* [ ] functions exported from a module are PascalCase
* [ ] classes and functional constructors are PascalCase
* [ ] functions declared in a class are camelCase
* [ ] variables declared inside a function are snake_case
* [ ] parameters declared in a function are camelCase

WIP: DATA AND COMMAND ABSTRACTIONS

A module or class API is a collection of methods that are designed to **communicate** its conceptual model of use. In object-oriented terms, I think of this as figuring out:

* what is its identity+role in an overall operation as well as its scope of responsibility.
* what type of command & control structure is it designed for? 
* how is command & control effected? lifecycle hook? reactive? imperative? asynchronous?
* what immediate systems does it report to, and how does that work with the type of C&C? push? hook? poll? call? callback?
* what immediate systems does it need to monitor to do its job, and how does that work with the type of C&C?  push? hook? poll? call? callback?

Knowing that, you can then design the API so the following is clear and consistent, and that its scope of responsibility continues to be clear:

* a model for its self-managed operations and data transformations
* a model for what conditions it delivers reliable operation and data
* a model for how it is managed by other system entities
* a model for how it manages other entities to meet its responsibilities

This is all very abstract, so we need to come up with canonical STEP-related concepts and patterns that are already in use.
