### ISSUE TITLE
Forage - [merged]

### ISSUE THREAD

**Issue by benloh** [theRAPTLab/gsgo#542]
_Merges dev-bl/forage -> dev_

Branch: `dev-bl/forage`

This adds predator foraging behavior, specifically script support for:
* `sees` -- Agents can `see` other agents
* `doesNotSee` -- Agents can 'not see' other agents
* `seekAgent` -- Seek nearest agent of a specific type
* `seekNearestVisible` -- Agents can find the nearest agent of specific type that is visible to it

This includes:
* A new `Vision` feature
* Major AI-focused changes to the `Movement` feature to centralize movement processing during specific game loop phases.
* Sim inputs (charcontrol) are now routed through Movement so that derived properties can be calculated.

# To Test

Basic Test

1. `git fetch && git checkout dev-bl/forage`
2. `npm run bootstrap && npm run gem`
3. Open `http://localhost/app/main?model=moths` -- You should see three trees with separate foliage and trunk colors, two small colored "moth" bees and one large "predator" bee.
4. Click "SETUP"
5. Click "+ Moth" a few times to add a bunch of moths -- They'll appear in random positions on the stage.
6. Click "SAVE" -- the moths will move positions because their random positions are set during the init script and the init script is re-run whenever you switch from SETUP to RUN modes.
7. Click "GO" to start the sim.
8. The large bee should start flying around the screen eating moths.  
  * Most moths should be slowly fade away but still be slightly visible so that we can tell what's going on.  (You can decide how faint you want the final script to be).
  * You'll see a blue vision cone in front of the predator so you can see what it sees.
  * Any moth that it sees will glow and become visible.
  * As the vision cone moves away, the moth will slow fade back to being "invisible".
  * The predator will pick the nearest moth it sees and go eat it.
  * If it cannot see a moth, it will wander until it sees one.

Char Control Moth

1. Reload Main
2. Open a new char control window `http://localhost/app/charcontrol`
3. Click "GO"
4. Move the moth around.  
  * The moth should turn and face the direction you're moving in.
  * Get the predator to chase you.  
  * Try to get in and out of the predator vision.

Char Control Predator

1. Reload Main
2. Open a new char control window `http://localhost/app/charcontrol`
3. Set the controller to "Predator"
4. On Main, click "SETUP" and add a bunch of moths, and click "SAVE"
5. Click "GO"
6. Move the predator around.
  * Move around and see how moths appear and disappear based on the vision cone.

# To Do
* [x] BUG: Changing a char control agent type does not reset opacity and colorization values. #201
* [x] BUG: After a run, instances cannot be added. #202
* [x] FIX: Input characters should rotate with each loop update and not just with the slower input updates.
* [x] Eating is problematic.  See #199.
* [ ] Char controlled moths cannot be eaten.  This requires #197 to be implemented.

---
---
---

# Vision Feature

Any agent that needs to see another agent needs to use the new Vision feature.  

Vision is implemented as a polygonal "cone" cast in front of the agent's current direction.  
* Direction is set by movement: it is the angle between the agent's last point and the current point.
* The width of the cone is hardcoded in the `agent.prop.Vision._viewAngle` property.  It's currently set to 90 degrees, 45 degrees to the left and right of the middle.
* The view distance is also hardcoded in `agent.prop.Vision_viewDistance`.  It's currently set to 250.
* The cone is not quite a triangle. We add an extra point to stretch out the center of the cone so that the view area is larger.  This is necessary because if you detect an agent on the edge of the cone, then turn towards the agent, turning will cause you to lose sight of the agent with a triangular vision area.

* Vision can be really difficult to debug, so we've hacked in a placeholder method that will draw the vision cone in front of the agent.  You can remove the vision cone by commenting out `feat-vision.ts:98`: `// agent.debug = visionPath;`

#### Syntax
`featCall Vision monitor <blueprint>`
where `<blueprint>` is the name of another blueprint, e.g. `Moth`.

This will register the agent with the Vision feature.  During the AGENTS_UPDATE loop, the system will update the agent with information about which other agents it can see.  Use the `sees` and `doesNotSee` conditions to test for visibility.

## `setViewDistance` method

Sets the distance, in sim units, that the agent can look ahead.

#### Syntax
`featCall Vision setViewDistance <number>`

Default: `250`

## `setViewAngle` method

Sets the angle, in degrees, of the vision cone.

### Syntax
`featCall Vision setViewAngle <number>`

Default: `90`

#### Syntax
`when <blueprintA> sees <blueprintB> [[ ... ]]`
where `<blueprint>` is the name of another blueprint, e.g. `Moth`.

This is a `when` condition test.  It requires that `<blueprintA>` have the `Vision` feature, otherwise `<blueprintB>` will never be seen.

#### Syntax
`when <blueprintA> doesNotSee <blueprintB> [[ ... ]]`
where `<blueprint>` is the name of another blueprint, e.g. `Moth`.

This is a `when` condition test.  It requires that `<blueprintA>` have the `Vision` feature, otherwise `<blueprintB>` will never be seen.

## Simple Example

The Vision feature works similar to the Touches feature in that you need to first register a target blueprint to monitor, and then you can use various conditional statements.

```
# BLUEPRINT Predator
# PROGRAM DEFINE
useFeature Vision
featCall Vision monitor Moth
# PROGRAM UPDATE
when Predator sees Moth [[
  featCall Moth.Costume setGlow 0.1
]]
```

---

# Movement Feature

Movement has been almost completely rewritten to properly make use of gameloop phases for FEATURES_UPDATE, FEATURES_THINK, and FEATURES_EXEC.  Now instead of actions executing immediately upon request, they are queued and executed during a specific phase.  This is more efficient (reduces extra looping) and better coordinates features.

Typically, movement is split into three phases:

1. A movement request might come in at any time.  It typically results in a `QueuePosition` call where the new position of the agent is requested.

2. `AGENTS_UPDATE` is fired, during which we process any vision updates, e.g. which agent can see which other agent.

3. `FEATURES_UPDATE` is fired, during which we pre-process information for FEATURES_THINK.  Currently this includes calculating distances between agents.

4. `FEATURES_THINK` is fired, during which we find target agents if we are supposed to seek one out (this depends the vision update above) and the selected movement type is calculated.  e.g. if the movement type is `wander` then we pick a random position/direction and queue the position call.

5. `FEATURES_EXEC` is fired, during which we calculate any derived properties from the movement.  e.g. `isMoving`, and orientation of the sprite.

6. `VIS_UPDATE` is fired, during which we actually apply the movement updates to the agent.  This is when position is actually set.  We do this during VIS_UPDATE and not FEATURES_EXEC because during the PRE_RUN loop (before GO is pushed) we need to be actively processing and updating input positions or else charcontrol (and PTrack and Pozyx) agents would not display.  FEATURES_EXEC is NOT run during PRE_RUN, but VIS_UPDATE is.

## Properties

There are a number of movement related properties that are worth noting.

* `direction` vs `agent.prop.Movement._orientation` vs `agent.orientation`
  - *direction* is movement related, *orientation* is purely visual.
  - `direction` is the angle (in degrees) the agent thinks it wants to move toward.  During `wander`, the agent will tend to continue moving in its current direction.  You can set this directly via script, e.g. `featCall Movement direction setTo 90`.  Note that setting this tells the agent the direction you want the agent to move in. The agent will not face this direction until it actually moves.
  - `agent.prop.Movement._orientation` is the angle (in radians) the agent should face.  `_orientation` is intended to be a private variable used only by the Movement and Vision features during internal calculations.  It is derived by calculating the angle from the last position of the agent to its current intended position.  Note that an agent can potentially be facing in one direction while moving in another (though this is not currently supported).  
  - `agent.orientation` is the angle (in radians) the agent will face.  Generally, `agent.prop.Movement._orientation` and `agent.orientation` are set at the same time during `FEATURES_EXEC`.  The agent property is used to set the rotation of the sprite visuals.  Since this is an agent property, you can set it directly, e.g. during an initScript, but during run time, it may be overwritten by Movement calculations.

* `distance` 
  - `distance` is the number of world units the sprite will travel each frame.  It is used by the various `seek`, `wander` and `moveEdgeToEdge` movement types.  The default is 0.5, but you can set this individually for any agent.
  - At a typical 30 fps:
    * `0.25` is a snail's pace
    * `1` is leisurely
    * `4` is medium
    * `8` is quick
    * `20` is fast
    * much more than 20 will feel hitchy

* `useAutoOrientation`
  - Agents no longer rotate automatically in the direction they are traveling by default.  If you want agents to auto-orient, you need to set the `useAutoOrientation` property to true.
  - e.g. `featProp Movement useAutoOrientation setTo true`

* `compassDirection`
  - This Movement feature property will return "E" or "W" depending on which direction the agent is facing.
  - The feature is customizable, so theoretically we can also add "N" and "S" if they are useful.  The ANGLES library just needs to be initialized appropriately.
  - Typically this would be used in an expression, e.g. 
  ```
  ifExpr {{ agent.propMovement.compassDirection.value === "E" }} [[
     featCall Costume setPose 2
  ]]
  ```
  - This is read-only.

## Do's and Don'ts

* DO NOT set x/y directly.  e.g. do not use `agent.x` to set position.  This bypasses any movement processing such as bounds testing and `isMoving` detection.  The main exception to this is during the init script it's OK to set position directly since that is just executed once before the sim starts.  There may be other similar circumstances where it's kosher to do this.
* DO use `queuePosition` to set movement.  See description below.
* DO use movementType to set movement.  In general, if you want an agent to move in a particular way, use a movement feature method.  This results in better coordination of properties and derived property updates during the correct phase.  The `setPosition` Movement feature method has been removed for this reason.

## `isMoving` property (read-only)

`isMoving` is a Movement feature property that you can use in expressions, e.g.
```
ifExpr {{ Moth.getFeatProp('Movement', 'isMoving').value }} [[
  // show flying pose
  featCall Moth.Costume setPose 4
]]
```

* The property is calculated during `FEATURES_EXEC` based on the new position set during `FEATURES_THINK`.
* To deal with jitter, an agent must move more than a minimum distance before it is considered a move.  Currently this value is set to 5.  This will probably need to be adjusted once we have real world PTrack and Pozyx input systems to test with.
* Currently we are not protecting the property so you can technically write to it, but the value will be overwritten with the next frame update.

## `seekNearest` method

Tells the agent to move directly toward the nearest agent of the target type, regardless of whether or not the target can be "seen".  If a target cannot be found, the agent will sit idly.

#### Syntax
`featCall Movement seekNearest <blueprint>`
where `<blueprint>` is the name of another blueprint, e.g. `Moth`.

The speed at which the agent is pursued is set via the `distance` property.
The nearest agent is selected with each loop update, so if another agent comes nearer, the seek will be revised to the nearer agent.

Example:
```
# BLUEPRINT Predator
# PROGRAM DEFINE
useFeature Movement
# PROGRAM INIT
// set the blueprint type of the target
featCall Movement seekNearest Moth
// set speed at which predator pursues target
featProp Movement distance setTo 1
```

## `seekNearestVisible` method

Tells the agent to move directly toward the nearest agent of the target type that is within the vision cone of the agent.  If a target cannot be found, the agent will revert to wandering until another agent is visible.

#### Syntax
`featCall Movement seekNearestVisible <blueprint>`
where `<blueprint>` is the name of another blueprint, e.g. `Moth`.

The speed at which the agent is pursued is set via the `distance` property.
The nearest agent is selected with each loop update, so if another agent comes nearer, the seek will be revised to the nearer agent.
See the Vision Feature for more details about how the vision cone is implemented.

Example:
```
# BLUEPRINT Predator
# PROGRAM DEFINE
useFeature Movement
# PROGRAM INIT
// set the blueprint type of the target
featCall Movement seekNearestVisible Moth
// set speed at which predator pursues target
featProp Movement distance setTo 1
```

#### Visibility

Note that the visibility of the target is derived programmatically, so a target with an alpha of 0, while not visible to students, is still visible to the agent. 

If you need to hide a target from an agent, one way to implement this is with an extra property, e.g.:
```
# BLUEPRINT Moth
addProp isVisibleToPredator Boolean false
```
```
# BLUEPRINT Predator
when Predator sees Moth [[
  ifExpr {{ Moth.getProp('isVisibleToPredator').value }} [[
    // eat
  ]]
]]
```

## `queuePosition` method

If you want to take advantage of any Movement feature (such as `isMoving` and automatic sprite orientation),   you should not set the agent position directly (e.g. via `prop x setTo nnn`).  Instead use `queuePosition`.  This will queue the position request until the proper phase and calculate any derived properties.

#### Syntax
`featCall Movement queuePosition <x> <y>`

where `<x>` and `<y>` are numeric position values.

(We may have to add separate x and y queuePosition methods if stack operations are needed to use calculcated values.)

## `jitterRotate` method

This will trigger a single random rotation of the sprite.  It's designed to be used within a conditional so you can trigger a series of random triggers.

#### Syntax
`featCall Movement jitterRotate`

#### Example
```
when Predator touchesCenterOf Moth [[
  featCall Moth.Movement jitterRotate
]]
```

---

# Costume Feature

## `flipX` and `flipY` property

Flip the sprite texture either along the x-axis or y-axis during Physics updates.

#### Syntax
`featProp Costume flipX setTo <boolean>`
where `<boolean>` is `true` or `false`.

Flipping is implemented by PIXIjs via a negative scale setting.  Setting this property to true will tell the Physics feature to use a negative scale when sizing the sprite.

Currently most Costume updates are handled by other Features, so setting this property will have no immediate effect.  We need to rewrite Costume do its own phase loop processing in order to do that.

#### To Use
1. Make sure Physics feature is enabled.
2. Set the property 

---

# Conditions

## `touchesCenterOf` condition

Like `touches` except that we test for the intersection of the physics body bounds of agent A against the center of agent B.  We use a 5 x 5 box around the center of B as the test to deal with jitter.

#### Syntax
`when <blueprintA> touchesCenterOf <blueprintB> [[ ... ]]`

## `isCenteredOn` condition

Like `touches` except that we test whether the distance between the centers of the physics bodies are within a distance of 5.  We probably need to adjust this based on jitter.

This works better for sprites (such as bees) that have a rather large bounding box.

#### Syntax
`when <blueprintA> isCenteredOn <blueprintB> [[ ... ]]`

---

# Examples

## Extended Example: Flashlight

This combines Vision and Movement features.

Here's one way to have predators "light up" Moths as they come into view.  We have moths by default slowly fade away to a low alpha value.  When they are seen by a predator, we set the minimum alpha to 1 so they are very visible.  When the predator loses sight of the Moth, we revert the alpha to the minimum value and let the it slowly fade away.

This approach is necessary because we have to also support fading and unfading when flying or resting on trees.

The code included here highlights the vision feature.  It will not run by itself.  See the `moths.js` file for the full code.

```
# BLUEPRINT Moth
# PROGRAM DEFINE
useFeature Costume
featCall Costume setCostume 'bee.json' 0
# PROGRAM UPDATE
ifExpr {{ agent.getFeatProp('Movement', 'isMoving').value }} [[
  // slowly fade in when moving
  prop alpha add 0.25
]]
every 0.25 [[
  // always slowly fade out
  prop alpha sub 0.1
]]
```

```
# BLUEPRINT Predator
# PROGRAM DEFINE
useFeature Physics
useFeature Touches
featCall Touches monitorTouchesWith Moth

// needed for Seek
useFeature Movement

useFeature Vision
featCall Vision monitor Moth

# PROGRAM UPDATE
when Predator sees Moth [[
  prop Moth.alpha setMin 1
  featCall Moth.Costume setGlow 0.1
]]
when Predator doesNotSee Moth [[
  prop Moth.alpha setMin 0.1
]]
when Predator touches Moth [[
  featCall Moth.Costume setGlow 1
  every 4 [[
    featCall Moth.Population removeAgent
    featCall Predator.Costume setGlow 1
  ]]
]]
```
